{{ if .Values.admissionControl.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: flink-operator-ca
  labels:
    app.kubernetes.io/name: flink-operator
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flink-operator-tls
  labels:
    app.kubernetes.io/name: flink-operator
spec:
  secretName: webhook-server-cert
  dnsNames:
  - flink-operator-webhook-service.{{ .Values.flinkOperatorNamespace.name }}.cainjector.svc
  issuerRef:
    name: flink-operator-ca
    kind: Issuer
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: flink-operator-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.flinkOperatorNamespace.name }}/webhook-server-cert
webhooks:
- clientConfig:
    service:
      name: flink-operator-webhook-service
      namespace: {{ .Values.flinkOperatorNamespace.name }}
      path: /mutate-flinkoperator-k8s-io-v1beta1-flinkcluster
  failurePolicy: Fail
  name: mflinkcluster.flinkoperator.k8s.io
  rules:
  - apiGroups:
    - flinkoperator.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinkclusters
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: flink-operator-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.flinkOperatorNamespace.name }}/webhook-server-cert
webhooks:
- clientConfig:
    service:
      name: flink-operator-webhook-service
      namespace: {{ .Values.flinkOperatorNamespace.name }}
      path: /validate-flinkoperator-k8s-io-v1beta1-flinkcluster
  failurePolicy: Fail
  name: vflinkcluster.flinkoperator.k8s.io
  rules:
  - apiGroups:
    - flinkoperator.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinkclusters
{{ end }}